progress stop

diff --git a/live-usb-maker-gui b/live-usb-maker-gui
--- a/live-usb-maker-gui
+++ b/live-usb-maker-gui
@@ -22,6 +22,8 @@ LOCK_FILE="/run/lock/$CLI_PROG"
 ERR_FILE="/var/log/$CLI_PROG.error"
 PROG_FILE="/var/log/$CLI_PROG.progress"
 
+USER_STOP=false
+
 TITLE=$"Live-USB Maker GUI"
 CHOOSE_MODE_TITLE=$"Live System Detected.  Select Live-USB creation mode"
 CHOOSE_MODE=$"Select Mode"
@@ -40,7 +42,8 @@ CLOSE=$"Close"
 ABOUT=$"About"
 HELP=$"Help"
 ADVANCE=$"Advanced"
-COMPLETE=$"Completed Succesfully!"
+COMPLETE=$"LiveUSB creation succesful!"
+STOP_MESSAGE=$"Operation stopped by user."
 
 PRETEND=$1
 echo "Pretend Mode = " $PRETEND
@@ -266,15 +269,23 @@ clean_up()
 
 error_notification()
 {
-if test -f $ERR_FILE; then 
-    echo "cli code had a fatal error"
-    MESSAGE="$(cat $ERR_FILE)"
-    yad --window-icon=drive-removable-media-usb --form --title="$INFO" --button=gtk-ok --text="$MESSAGE" --buttons-layout=center
-    actionstatus=0
-else
-    echo "cli code ran without error"
-    yad --window-icon=drive-removable-media-usb --form --title="$INFO" --button=gtk-ok --text="$COMPLETE" --buttons-layout=center
+
+if [ $USER_STOP = true ]; then
+    yad --window-icon=drive-removable-media-usb --width=300 --align=center --form --title="$INFO" --button=gtk-ok --buttons-layout=center --field="<b>$STOP_MESSAGE</b>":LBL ""
     actionstatus=1
+fi
+
+if [ $USER_STOP = false ]; then    
+    if test -f $ERR_FILE; then 
+        echo "cli code had a fatal error"
+        MESSAGE="$(cat $ERR_FILE)"
+        yad --window-icon=drive-removable-media-usb --width=300 --form --title="$INFO" --button=gtk-ok --text="$MESSAGE" --buttons-layout=center
+        actionstatus=0
+    else
+        echo "cli code ran without error"
+        yad --window-icon=drive-removable-media-usb --width=300 --align=center --form --title="$INFO" --button=gtk-ok --buttons-layout=center --field="<b>$COMPLETE</b>":LBL ""
+        actionstatus=1
+    fi
 fi
 }
 
@@ -288,8 +299,7 @@ local lum_pid yad_pid tail_pid
         yad_pid=$!
 
         tail -n20  -f --pid=$yad_pid $PROG_FILE >&10 &
-	tail_pid=$!
-
+	
         if [ -z "$lum_pid" ]; then 
             $CLI_PROG gui $PRETEND --force=flock --from="$source" -t /dev/$usb_device 2>/dev/null &
             lum_pid=$!
@@ -310,7 +320,15 @@ local lum_pid yad_pid tail_pid
         test -d /proc/$lum_pid || echo "lum exited"
 
         if test -d /proc/$lum_pid; then
-           YES_no "Do you want to keep going?" || break
+           yad --window-icon=drive-removable-media-usb --width=300 --align=center --form --title="$INFO" --button=$"No"!gtk-close!:1 --button=$"Yes"!gtk-ok!:0 --buttons-layout=center --field=$"Progress window closed, but job not done. Do you want to keep going?":LBL ""
+#	   YES_no "Do you want to keep going?" || break
+           case $? in
+
+                0) continue ;;
+                1) USER_STOP=true && break ;;
+
+           esac
+               
            kill -CONT $lum_pid
            continue
         else
@@ -322,13 +340,22 @@ local lum_pid yad_pid tail_pid
     #read x
     echo "killing yad and lum as needed  ..."
 	
-    sleep 2
+    sleep 1
 
     # I don't know why I no longer get the Terminate message
-    kill $tail_pid 2>/dev/null
-    kill $yad_pid 2>/dev/null
-    kill $lum_pid 2>/dev/null
+    kill_pids $yad_pid $lum_pid
 }
+
+kill_pids() {
+    local pid
+    for pid; do
+        test -z $pid && continue
+        disown  $pid 2>/dev/null
+        pkill --parent $pid 
+        kill    $pid 2>/dev/null
+    done
+}
+
 #launch gui
 
 main "$@"
